language: elixir
elixir:
 - 1.2.6
 - 1.3.2
 - 1.4.5
 - 1.5.1

otp_release:
 - 18.2.1
 - 19.0
 - 20.0

matrix:
  exclude:
    - elixir: 1.2.6
      otp_release: 20.0
    - elixir: 1.3.2
      otp_release: 20.0

services:
  - postgresql
